# Generated by Django 4.2.4 on 2023-09-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0002_producto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='id',
        ),
        migrations.AddField(
            model_name='producto',
            name='codigo',
            field=models.CharField(default='ValorPredeterminado', max_length=10, primary_key=True, serialize=False),
        ),
    ]
