# Generated by Django 4.2.4 on 2023-09-02 13:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0003_remove_producto_id_producto_codigo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='codigo',
            new_name='dni',
        ),
    ]
