# Generated by Django 4.2.4 on 2023-09-02 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0004_rename_codigo_cliente_dni'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ruc', models.CharField(max_length=10, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('rubro', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=10)),
            ],
        ),
    ]
