# Generated by Django 3.2 on 2023-09-05 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0006_auto_20230905_1428'),
    ]

    operations = [
        migrations.AddField(
            model_name='venta',
            name='costo_total',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='venta',
            name='fecha',
            field=models.DateField(auto_now_add=True),
        ),
    ]
