# Generated by Django 3.2 on 2023-09-05 22:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0007_auto_20230905_1445'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='venta',
            name='productos',
        ),
        migrations.DeleteModel(
            name='DetalleVenta',
        ),
        migrations.DeleteModel(
            name='Venta',
        ),
    ]
