# Generated by Django 4.1.7 on 2023-09-08 05:59

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Academico', '0013_venta'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='venta',
            name='fecha_venta',
        ),
        migrations.AddField(
            model_name='venta',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='venta',
            name='producto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Academico.producto'),
        ),
        migrations.AlterField(
            model_name='venta',
            name='cantidad',
            field=models.IntegerField(),
        ),
    ]
